### ISSUE TITLE
-o i don't understand

### ISSUE THREAD

**Issue by BlazeVertex** [iWas-Coder/web-dl#1] opened 2022-10-03 18:25 UTC
...URL..................../remix.ism/.mpd `-o C:\Users\test-\Videos\output` when i come to output it fails and says

The system cannot find the specified path.

 what do i do wrong

![Uploading Schermafbeelding 2022-10-03 202523.png…]()

**Comment by iWas-Coder** [comment] 2022-10-03 20:36
Hello! Thank you very much for posting! I created this repo as a personal project but I really enjoy that someone gets interested about it :) If you have any suggestion, do not hesitate to make a pull request, I would appreciate it!

According to the problem that you have encountered, I imagine you are using Windows, aren't you? Could you post here the error log that outputs (for some reason I can't see the image :/).. thanks!!

**Comment by iWas-Coder** [comment] 2022-10-03 20:59
Also, I coded the downloader part using yt-dlp and aria2c, and I am migrating to ffmpeg as it is more reliable and easier to use.
PD: the '-o' argument was designed to pass a filename (e.g. test.mkv), and not a path, as it saves it automatically to the 'out' directory of the project.

**Comment by BlazeVertex** [comment] 2022-10-04 06:19
[![Schermafbeelding-2022-10-04-081822.png](https://i.postimg.cc/wvdZPTcT/Schermafbeelding-2022-10-04-081822.png)](https://postimg.cc/f3B8Ssr6)

idk where that log file is saved bcs i cant find it

**Comment by iWas-Coder** [comment] 2022-10-04 08:47
I implemented the download part fully with ffmpeg libs, now you could do "python3 web-dl.py -u <URL> -o test.mkv" and it should download the fully merged video+audio in the cache dir of the project (ensure you have ffmpeg installed on your system!!)

**Comment by iWas-Coder** [comment] 2022-10-04 08:49
Remember that this project is currently under developement, so it is no near finished or polished :D

**Comment by BlazeVertex** [comment] 2022-10-04 10:43
[![Schermafbeelding-2022-10-04-124119.png](https://i.postimg.cc/9MXGh9MD/Schermafbeelding-2022-10-04-124119.png)](https://postimg.cc/XZhZKp9W)

Everything seems to go right but it stays in : C:\Users\test-\Downloads\Compressed\web-dl-main\web-dl-main\cache
and nothing in output folder

edit : also get this Warning: program compiled against libxml 211 using older 209

Image is for the output that stays in cache

**Comment by iWas-Coder** [comment] 2022-10-04 11:32
Yeah, for now I only have implemented the download part.
It shows like this because the content declared by the manifest (.MPD) has some sort of protection (CENC Encryption). So, it needs to be decrypted to play nicely :)
I will continue to work on it, it is not finished yet!!

PD: Could you post the output for the warning of 'libxml'? It would help a lot!

**Comment by BlazeVertex** [comment] 2022-10-04 14:11
`PD: Could you post the output for the warning of 'libxml'? It would help a lot!`

so what do i need to send that cache file bcs that was the output it gave that video

**Comment by BlazeVertex** [comment] 2022-10-04 14:11
if i ever can help and if you need my discord, i will put it here if ya want

**Comment by iWas-Coder** [comment] 2022-10-04 19:01
Yeah, totally! You can email me to wasymatieh01@gmail.com so as not to post it here for everyone ;)
Thanks a lot again!

**Closed as completed by iWas-Coder** 2022-10-04 19:01 UTC
