### ISSUE TITLE
KeyError: 'duration'

### ISSUE THREAD

**Issue by Drommer** [iWas-Coder/web-dl#5] opened 2023-10-22 23:57 UTC
I'm using Arch Linux. The dependencies from requirements.txt are installed. The URL is recognized, the files are downloaded, but then I get the following error: 

```
Traceback (most recent call last):
File "/home/dr0mmer/web-dl/./web-dl.py", line 49, in <module>
main()
File "/home/dr0mmer/web-dl/./web-dl.py", line 35, in main
video_keys, audio_keys = decryptor.extract_keys(args.url())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/dr0mmer/web-dl/modules/decryptor.py", line 42, in extract_keys
if 'H' in period.attrib['duration']:
~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'duration'
```

Can you tell me what I'm doing wrong? Maybe I need to install some other Python module?

[My manifest.mpd](https://github.com/iWas-Coder/web-dl/files/13064893/manifest.mpd.txt)

**Comment by iWas-Coder** [comment] 2023-10-23 00:08
Hello! First of all, thanks a lot for posting an issue, it's super cool seeing people interested in the project, even in this very early stage of the development!! :D

It would be helpful if you could post the entire command you tried to execute, as well as the URL you tried to hit where the MPD manifest should be hosted (in XML).
Thanks!! :))

**Comment by Drommer** [comment] 2023-10-23 00:16
My line:
`./web-dl.py -u 'https://vod20.sweet.tv/wvdash/16444/mGrCgUBOroik0I8O7FUgXv9WhffZBY4Gqijg7_H6sqfnmcTOtK69LTSO_B8O_xMm3HDgy3yvDVmKbHE/manifest.mpd' -o /tmp/TEST.mp4`

It's UA streaming service. You must create an account and make a payment to access this content.

**Comment by iWas-Coder** [comment] 2023-10-23 00:38
In the manifest you provided, in the 'Period' object (there is only one), there is not any attribute specifying its duration, this is why it crashes, because in the code I lookup that attribute in order to select the appropiate 'Period' in the manifest (I've seen several with a second 'Period' of a few seconds long, which it not wanted).

This is very interesting, I'm going to develop a fix for this case, so it picks the duration from the top-level object, instead of from the 'Period' objects. Again, thanks a lot for posting!!!

I'll leave this issue opened while I work on this; as soon as I make some progress I'll log it here, until it is fully functional :D

**Comment by Drommer** [comment] 2023-10-23 01:24
Thanks, I'll wait for that.

I would also suggest to make it possible to pass parameters to yt-dlp through a separate argument (e.g. to be able to select specific video/audio streams or the number of fragments to download simultaneously), and also the possibility to assign a separate directory for temporary files (e.g. /tmp).

**Comment by iWas-Coder** [comment] 2023-10-23 02:03
I'll also start (tomorrow) with the parameter to set the cache files to go on (by default being `./cache`).

In the mean time, take a look at the new commit, and report anything new that you might encounter :)
Keep in mind that the actual decryption is still a job to be done, and to think about it, so for now is not functional; but everything else yes!! Thanks again!

**Comment by Drommer** [comment] 2023-10-23 02:08
Well, the previous problem seems to be solved. However, the issue is now at the merge stage. ~~Is there any way I can get more information?~~ I looked at the source code and saw that the decryptor is not finished yet. So everything works fine at this stage?
![error](https://github.com/iWas-Coder/web-dl/assets/36813829/55fcecef-0818-4eb9-a5a4-f9aaba29591d)

**Comment by iWas-Coder** [comment] 2023-10-23 02:22
Yeah, I should probably replace that with a more meaningful error; the problem is what I've told you before: the actual decryption of the media.

If you look in the `./cache` dir, it must be 2 encrypted files, corresponding to both the video and audio selected tracks (need to improve that too).

So what is left is to somehow make a legitimate request from the browser, and intercept the response before the local player gets it back, and, in theory, there should be the decryption key. But again, this is still a big TODO.

I'll leave this issue opened for a couple of days more, if any similar problems occur in this time. I'll implement the features you mentioned, as they seem quite nice to have :)
Also, if wanted, any contributions (PRs) are very much appreciated by all means.

**Comment by Drommer** [comment] 2023-10-23 02:36
Are there any approximate timelines for when decryption can be implemented? Unfortunately, I don't understand well enough how the key is generated. Is it just a matter of intercepting the request/response, or are additional actions required to obtain the key?

**Comment by iWas-Coder** [comment] 2023-10-30 09:47
Don't know for sure, as it is quite a challenge (for me at least), but is a very interesting project that I seek to drive it to a more robust state, while learning a lot in the process. I'll continue developing the project fairly often, combining it with other projects I'm currently working on; and the research of the theoretical part will be done in the wiki section of this repository here on GH.

Thanks for all! :D

**Closed as completed by iWas-Coder** 2023-10-30 09:47 UTC
